# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.15.3
      - image: trufflesuite/ganache-cli
        command: ganache-cli -p 8545 --gasLimit 20000000 --gasPrice 20000 --defaultBalanceEther 1000000000 --allowUnlimitedContractSize -a 20
    steps:
      - run: |
          sudo apt-get install libudev-dev
          sudo apt install libusb-1.0-0
          sudo wget https://github.com/ethereum/solidity/releases/download/v0.5.16/solc-static-linux -O /usr/local/bin/solc
          sudo chmod +x /usr/local/bin/solc
      - checkout          
      - run:
          name: Get compound-protocol
          command: git submodule update --init --recursive
      - run:
          name: Generate checksum
          command: shasum package.json compound-protocol/package.json > checksum.tmp
      - restore_cache:
          key: dependency-cache-{{ checksum "checksum.tmp" }}
      - run:
          name: Install packages
          command: |            
            npm install
      - run:
          name: Compile contracts
          command: npx hardhat compile
      - run:
          name: Generate TypeChain typings
          command: npx hardhat typechain
      - run:
          name: Run tests
          command: sh runtest.sh
      - save_cache:
          key: dependency-cache-{{ checksum "checksum.tmp" }}
          paths:
            - node_modules
            - compound-protocol/node_modules
